spring:
  datasource:
    url: jdbc:mysql://localhost:3306/new_posts?useSSL=false
    username: root
    password: 3141592653
    driverClassName: com.mysql.cj.jdbc.Driver
    validationQuery: SELECT 1
    platform: mysql
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      dll-auto: update
    properties:
      hibernate:
        id:
          new_generator_mappings: false
        order_inserts: true
        order_updates: true
        show_sql: true
        format_sql: false
        generate_statistics: false
        jdbc:
          batch_size: 20
          batch_versioned_data: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect